DROP TABLE IF EXISTS PROJECTS;
DROP SEQUENCE IF EXISTS GLOBAL_SEQ;

CREATE SEQUENCE GLOBAL_SEQ START 100000;

CREATE TABLE PROJECTS
(
  id         INTEGER PRIMARY KEY DEFAULT nextval('GLOBAL_SEQ'),
  name        VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  modified    TIMESTAMP NOT NULL  DEFAULT now(),
  manager     VARCHAR NOT NULL
);
